name: Deploy docs

on:
    pull_request:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Noje.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: "npm"
                  cache-dependecy-path: "**/package-lock.json"

            - run: npm ci

            - run: npm run build
              env:
                  TURBO_TOKEN: q0DXFyxT0zJKs0oKnYXzC2n0
                  TURBO_TEAM: sergiotrajano

            - name: Deploy storybook
              working-directory: ./packages/docs
              run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
              env:
                  GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
